safe: true
url: "http://dryha.com"
image_path: "/gallery/images/"
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']