publishDir = "docs"
favicon = "favicon.png"
title = "Zhanna Dryha"
baseURL = "http://dryha.com/"
tags = ["portfolio", "digital art", "traditional art"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-47871671-1"
disqusShortname = "zhanna dryha"
disableKinds = ["blog", "taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Zhanna Dryha"
    author = "Zhanna Dryha"
    description = "Professional Artist."
    logoBig = "/images/zhanna_bayern-2017_circle.jpg"
    logoSmall = "/images/zhanna_bayern-2017_circle.jpg"
    favicon = "favicon.ico"
    opengraphImage = "/images/zhanna_bayern-2017_circle.jpg"
    linkedin = "dryha"
    facebook = "https://www.facebook.com/zhanna.dryha"
    email = "zhanna@dryha.com"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = false
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 1
[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 2
