favicon = "favicon.png"
title = "Zhanna Dryha"
baseURL = "https://dryha.com"
tags = ["portfolio", "digital art", "traditional art"]
disableKinds = ["blog", "taxonomy", "taxonomyTerm"]
publishDir = "docs"
cleanDestinationDir = true